### ISSUE TITLE
Doesn't work with Unity 2019.3.x no domain reload, no scene reload

### ISSUE THREAD

**Issue by hcorion** [benoit-dumas/DebugPlus#6]
It works normally if *Enter Play Mode Options (Experimental)* is unchecked. It also works normally the first time you play the game with the option checked.
But after you enable that option and play the game once more, you get the following errors:
```sql
Single instance of DebugPlusNS.LogDrawer already destroyed on application quit. Won't create again - returning null.
UnityEngine.Debug:LogWarning(Object)
DebugPlusNS.SingletonBehavior`1:get_I() (at Assets/3rdparty/DebugPlus/Scripts/SingletonBehavior.cs:12)
DebugPlusNS.LogDrawer:Log(LogEntry) (at Assets/3rdparty/DebugPlus/Scripts/LogDrawer.cs:75)
DebugPlus:LogOnScreen(String) (at Assets/3rdparty/DebugPlus/Scripts/DebugPlus.cs:182)
```
and 
```sql
NullReferenceException: Object reference not set to an instance of an object
DebugPlusNS.LogDrawer.Log (DebugPlusNS.LogEntry logEntry) (at Assets/3rdparty/DebugPlus/Scripts/LogDrawer.cs:75)
DebugPlus.LogOnScreen (System.String text) (at Assets/3rdparty/DebugPlus/Scripts/DebugPlus.cs:182)
```

It seems like your SingletonBehavior functionality is not working properly.

Tested on Unity 2019.3.2f1

**Comment by methusalah** [comment]
I don't know the no domain/no scene reload, but i'm guessing that the awake method is called again at least.

could you try adding that to SingletonBehaviour? I can't test myself right now.
```
private void Awake() {
    applicationIsQuitting = false;
}
```

**Comment by hcorion** [comment]
Hmm, yeah Awake is not getting called the second run. The first run I call Awake is called properly.

**Comment by methusalah** [comment]
Awake is supposed to be the opposite of Destroy, phylosophicaly, in the [Unity order of execution doc](https://docs.unity3d.com/Manual/ExecutionOrder.html). If the Destroy is called, but the Awake is not called again, then we got a problem. I suppose it's one of the reasons why this feature is flagged "experimental".

Is the start called again?

We can try and use the event MonoBehaviour.OnApplicationQuit() instead of Destroy, but I will have to think more about it.

**Comment by methusalah** [comment]
fixed in recent update
